// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Helpers = require("./helpers");

function createCommandSequence(_, args) {
  var commandSequenceInput = args.sequence;
  var commandSequence = Helpers.injectIdToObjTree(commandSequenceInput);
  var path = "src/command_sequence/" + (commandSequence.id + ".json");
  return Helpers.writeJsonFile(path, commandSequence).then((function (path) {
                return Helpers.readJsonFile(path);
              }));
}

function resolvers() {
  return {
          createCommandSequence: createCommandSequence
        };
}

exports.createCommandSequence = createCommandSequence;
exports.resolvers = resolvers;
/* ./helpers Not a pure module */
