// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Helpers = require("./helpers");
var Uplink$HoustonPocReasonml = require("../uplink/Uplink.bs.js");

function createCommandSequence(_, args) {
  var commandSequenceInput = args.sequence;
  var commandSequence = Helpers.injectIdToObjTree(commandSequenceInput);
  var path = "src/command_sequence/" + (commandSequence.id + ".json");
  return Helpers.writeJsonFile(path, commandSequence).then((function (path) {
                return Helpers.readJsonFile(path);
              }));
}

function executeCommandSequence(store) {
  var uplink = Uplink$HoustonPocReasonml.uplink(store);
  return (function (_, args) {
      var path = "src/command_sequence/" + (args.id + ".json");
      return Helpers.readJsonFile(path).then((function (sequence) {
                    var match = Curry._1(uplink, sequence);
                    Curry._1(match[0], /* () */0);
                    return Promise.resolve(true);
                  }));
    });
}

function resolvers(store) {
  return {
          createCommandSequence: createCommandSequence,
          executeCommandSequence: executeCommandSequence(store)
        };
}

exports.createCommandSequence = createCommandSequence;
exports.executeCommandSequence = executeCommandSequence;
exports.resolvers = resolvers;
/* ./helpers Not a pure module */
