// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Helpers = require("./helpers");

function resolvers() {
  return {
          findCommandSequence: (function (_, args) {
              return Helpers.readJsonFile("src/command_sequence/" + (args.id + ".json"));
            })
        };
}

exports.resolvers = resolvers;
/* ./helpers Not a pure module */
