// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var resolvers = {
  info: (function () {
      return "Houston ReasonML PoC: Houston is SFU Satellite design team's ground control station";
    })
};

exports.resolvers = resolvers;
/* No side effect */
