// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Query$HoustonPocReasonml = require("./Query.bs.js");
var State$HoustonPocReasonml = require("../store/reducers/State.bs.js");
var Store$HoustonPocReasonml = require("../store/Store.bs.js");
var Reducer$HoustonPocReasonml = require("../store/reducers/Reducer.bs.js");
var Mutation$HoustonPocReasonml = require("./Mutation.bs.js");
var Subscription$HoustonPocReasonml = require("./Subscription.bs.js");

function init(pubsub) {
  var store = Store$HoustonPocReasonml.create(Reducer$HoustonPocReasonml.reducer, State$HoustonPocReasonml.initialState);
  Store$HoustonPocReasonml.subscribe(store, (function (state) {
          pubsub.publish("STATE", Subscription$HoustonPocReasonml.mapToSchemaState(state));
          return /* () */0;
        }));
  return {
          Query: Query$HoustonPocReasonml.resolvers(store),
          Mutation: Mutation$HoustonPocReasonml.resolvers(store),
          Subscription: Subscription$HoustonPocReasonml.resolvers(pubsub)
        };
}

exports.init = init;
/* Query-HoustonPocReasonml Not a pure module */
