// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Subscription = require("./Subscription");
var Query$HoustonPocReasonml = require("./Query.bs.js");
var State$HoustonPocReasonml = require("../store/reducers/State.bs.js");
var Store$HoustonPocReasonml = require("../store/Store.bs.js");
var Reducer$HoustonPocReasonml = require("../store/reducers/Reducer.bs.js");
var Mutation$HoustonPocReasonml = require("./Mutation.bs.js");

var publish = ((pubsub, serializableState) => { pubsub.publish("STATE", serializableState)});

function init(pubsub) {
  var store = Store$HoustonPocReasonml.create(Reducer$HoustonPocReasonml.reducer, State$HoustonPocReasonml.initialState);
  Store$HoustonPocReasonml.subscribe(store, (function (state) {
          return Curry._2(publish, pubsub, {
                      state: State$HoustonPocReasonml.stateToJs(state)
                    });
        }));
  return {
          Query: Query$HoustonPocReasonml.resolvers(store),
          Mutation: Mutation$HoustonPocReasonml.resolvers(store),
          Subscription: Subscription.subscriptions
        };
}

exports.publish = publish;
exports.init = init;
/* publish Not a pure module */
