// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Subscription = require("./Subscription");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var Query$HoustonPocReasonml = require("./Query.bs.js");
var State$HoustonPocReasonml = require("../store/reducers/State.bs.js");
var Store$HoustonPocReasonml = require("../store/Store.bs.js");
var Reducer$HoustonPocReasonml = require("../store/reducers/Reducer.bs.js");
var Mutation$HoustonPocReasonml = require("./Mutation.bs.js");

var publish = ((pubsub, serializableState) => { pubsub.publish("STATE", serializableState)});

function serialize(param) {
  var uplink = param[/* uplink */0];
  return {
          state: {
            uplink: {
              sequenceId: Js_null_undefined.fromOption(uplink[/* sequenceId */0]),
              pending: $$Array.of_list(uplink[/* pending */1]),
              unresolved: $$Array.of_list(uplink[/* unresolved */2]),
              successful: $$Array.of_list(uplink[/* successful */3]),
              failed: $$Array.of_list(uplink[/* failed */4]),
              inProgress: uplink[/* inProgress */5]
            }
          }
        };
}

function init(pubsub) {
  var store = Store$HoustonPocReasonml.create(Reducer$HoustonPocReasonml.reducer, State$HoustonPocReasonml.initialState);
  Store$HoustonPocReasonml.subscribe(store, (function (state) {
          return Curry._2(publish, pubsub, serialize(state));
        }));
  return {
          Query: Query$HoustonPocReasonml.resolvers(store),
          Mutation: Mutation$HoustonPocReasonml.resolvers(store),
          Subscription: Subscription.subscriptions
        };
}

exports.publish = publish;
exports.serialize = serialize;
exports.init = init;
/* publish Not a pure module */
