// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function resolvers(pubsub) {
  return {
          state: {
            subscribe: (function () {
                return pubsub.asyncIterator("STATE");
              })
          }
        };
}

function mapToSchemaState(param) {
  var uplink = param[/* uplink */0];
  return {
          state: {
            uplink: {
              sequenceId: Js_null_undefined.fromOption(uplink[/* sequenceId */0]),
              pending: $$Array.of_list(uplink[/* pending */1]),
              unresolved: $$Array.of_list(uplink[/* unresolved */2]),
              successful: $$Array.of_list(uplink[/* successful */3]),
              failed: $$Array.of_list(uplink[/* failed */4]),
              inProgress: uplink[/* inProgress */5]
            }
          }
        };
}

exports.resolvers = resolvers;
exports.mapToSchemaState = mapToSchemaState;
/* No side effect */
