// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");

function create(reducer, initialState) {
  return /* record */[
          /* state */[initialState],
          /* reducer */reducer,
          /* observers */[/* [] */0]
        ];
}

function dispatch(param, action) {
  var state = param[/* state */0];
  var newState = Curry._2(param[/* reducer */1], state[0], action);
  state[0] = newState;
  return List.iter((function (obs) {
                return Curry._1(obs, newState);
              }), param[/* observers */2][0]);
}

function getState(store) {
  return store[/* state */0][0];
}

function subscribe(param, listener) {
  var observers = param[/* observers */2];
  observers[0] = /* :: */[
    listener,
    observers[0]
  ];
  return /* () */0;
}

exports.create = create;
exports.dispatch = dispatch;
exports.getState = getState;
exports.subscribe = subscribe;
/* No side effect */
