// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

var initialUplinkState = /* record */[
  /* sequenceId : None */0,
  /* pending : [] */0,
  /* unresolved : [] */0,
  /* successful : [] */0,
  /* failed : [] */0,
  /* inProgress */false
];

var initialState = /* record */[/* uplink */initialUplinkState];

function serialize(param) {
  var uplink = param[/* uplink */0];
  return {
          state: {
            uplink: {
              sequenceId: Js_null_undefined.fromOption(uplink[/* sequenceId */0]),
              pending: $$Array.of_list(uplink[/* pending */1]),
              unresolved: $$Array.of_list(uplink[/* unresolved */2]),
              successful: $$Array.of_list(uplink[/* successful */3]),
              failed: $$Array.of_list(uplink[/* failed */4]),
              inProgress: uplink[/* inProgress */5]
            }
          }
        };
}

exports.initialUplinkState = initialUplinkState;
exports.initialState = initialState;
exports.serialize = serialize;
/* No side effect */
