// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var initialUplinkState = /* record */[
  /* sequenceId : None */0,
  /* pending : [] */0,
  /* unresolved : [] */0,
  /* successful : [] */0,
  /* failed : [] */0,
  /* inProgress */false
];

function stateToJs(param) {
  return {
          uplink: param[/* uplink */0]
        };
}

function stateFromJs(param) {
  return /* record */[/* uplink */param.uplink];
}

var initialState = /* record */[/* uplink */initialUplinkState];

exports.initialUplinkState = initialUplinkState;
exports.stateToJs = stateToJs;
exports.stateFromJs = stateFromJs;
exports.initialState = initialState;
/* No side effect */
