// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


var initialUplinkState = /* record */[
  /* sequenceId : None */0,
  /* pending : [] */0,
  /* unresolved : [] */0,
  /* successful : [] */0,
  /* failed : [] */0,
  /* inProgress */false
];

var initialState = /* record */[/* uplink */initialUplinkState];

exports.initialUplinkState = initialUplinkState;
exports.initialState = initialState;
/* No side effect */
